spring.application.name=Employee-Api

spring.profiles.active=test

#JPA는 지연로딩 할 객체를 만났을 때 default_batch_fetch_size개수만큼 모일 때까지 쌓아두었다가,
#해당 개수가 다 모이면 쿼리를 보낸다
#default_batch_fetch_size 설정하기 (N+1 문제 보완해주는 설정)
spring.jpa.properties.hibernate.default_batch_fetch_size=100